language: cpp
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

compiler:
  - g++-6

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .
